id: A399B4B4E
title: Invoking the Blessings of the Kagyü Lineage—‘Dorjechang Thungma’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:02:37.649549
  last_modified_at: 2022-03-01 04:02:37.649556
