id: A399B4B4E
title: Prayer to the Kagyü Masters
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:02:37.651835
  last_modified_at: 2022-03-01 04:02:37.651838
